baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Organ Studies'
disqusShortname = "OS"
enableGitInfo = true

[params]
BookTheme = 'auto'
BookToC = true
BookLogo = 'favicon.png'
BookSection = 'docs'
BookRepo = 'https://github.com/alex-shpak/hugo-book'
BookCommitPath = 'commit'
BookDateFormat = 'Jan 2, 2006'
BookSearch = true
BookComments = false


[outputs]
  home = ["HTML", "RSS"]

[comments]
enabled = true
provider = "waline"


